// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8QdCUpUMo5PqQM4sI2opd76aLS9OmHjI',
    appId: '1:119430690777:web:bd29e7cd177ff2f6e64bc8',
    messagingSenderId: '119430690777',
    projectId: 'snapseek-cf1e8',
    authDomain: 'snapseek-cf1e8.firebaseapp.com',
    storageBucket: 'snapseek-cf1e8.appspot.com',
    measurementId: 'G-BXCTLD54XK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6FIjy5DqtS5EPZwuS9PsFNcXv47PKk6k',
    appId: '1:119430690777:android:2fb583200eabd550e64bc8',
    messagingSenderId: '119430690777',
    projectId: 'snapseek-cf1e8',
    storageBucket: 'snapseek-cf1e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtffyDcO-pjIXdD_wHqBfgcXMIC9d0azQ',
    appId: '1:119430690777:ios:356bcac5d7c94407e64bc8',
    messagingSenderId: '119430690777',
    projectId: 'snapseek-cf1e8',
    storageBucket: 'snapseek-cf1e8.appspot.com',
    iosBundleId: 'com.example.snapseek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtffyDcO-pjIXdD_wHqBfgcXMIC9d0azQ',
    appId: '1:119430690777:ios:356bcac5d7c94407e64bc8',
    messagingSenderId: '119430690777',
    projectId: 'snapseek-cf1e8',
    storageBucket: 'snapseek-cf1e8.appspot.com',
    iosBundleId: 'com.example.snapseek',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD8QdCUpUMo5PqQM4sI2opd76aLS9OmHjI',
    appId: '1:119430690777:web:0a3a96adb9f69789e64bc8',
    messagingSenderId: '119430690777',
    projectId: 'snapseek-cf1e8',
    authDomain: 'snapseek-cf1e8.firebaseapp.com',
    storageBucket: 'snapseek-cf1e8.appspot.com',
    measurementId: 'G-EQHE61LZ9P',
  );
}
